screenSize:
  width: 470
  height: 700
scout:
  scoutCampPos:
    x: 553
    y: 70
  investigation: true

feature:
  gather-resource:
    enable: true
    use-secondary-commander: false
  alliance-help:
    enable: true
