screenSize:
  width: 470
  height: 850
scout:
  scoutCampPos:
    x: 553
    y: 70
  investigation: true
  mailPos:
    x:
    y:
  reportsPos:
    x:
    y:
  centerPos:
    x:
    y:
method: "none"
haoiUser: null
haoiRebate: null
twocaptchaKey: ""